# Generated by Django 4.2.10 on 2024-05-30 01:49

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime.now,
                verbose_name="Registrado em",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
